name=ConsentiumThings
version=3.0.0
includes=ConsentiumThings.h
author=Consentium IoT
maintainer=Consentium IoT<official@consentiumiot.com>
sentence=Consentium Things IoT board.
paragraph=This library runs IoT applications on ESP 32 class of microcontrollers. 
category=Data Processing
url=https://github.com/ConsentiumIoT/ConsentiumThings
architectures=esp32
depends=ArduinoJson, Adafruit ADS1X15, WiFiManager
